# Site settings
title: "How to Fit a Straight Line"
email: anna.scaife@manchester.ac.uk
description: "Like the title says..."
baseurl: "/straight-line"
url: "http://as595.github.io"
twitter_username: radastrat
github_username:  as595

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
